"""Added player_symbol column to Game model

Revision ID: 84ea28710310
Revises: 37e51c6d5037
Create Date: 2025-03-20 15:55:43.808614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84ea28710310'
down_revision = '37e51c6d5037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_symbol', sa.String(length=1), nullable=False))
        batch_op.alter_column('result_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('result_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('player_symbol')

    # ### end Alembic commands ###
